import type { Metadata } from "next";
import { Roboto_Mono as font } from "next/font/google";
import "./globals.css";

const myfont = font({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={myfont.className}>{children}</body>
    </html>
  );
}
